Show requirements for binaries

diff --git a/bin/prettyjson b/bin/prettyjson
--- a/bin/prettyjson
+++ b/bin/prettyjson
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! type xmllint > /dev/null 2>&1; then
+  echo 'python 2.7 or higher is required to run this'
+  exit 1
+fi
+
 if [ -t 0 ]; then
   if [ $# -gt 0 ]; then
     echo "$*" | python -m json.tool
diff --git a/bin/prettyxml b/bin/prettyxml
--- a/bin/prettyxml
+++ b/bin/prettyxml
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if ! type xmllint > /dev/null 2>&1; then
+  echo 'libxml2 is required to run this'
+  exit 1
+fi
+
 if [ -t 0 ]; then
   if [ $# -gt 0 ]; then
     echo "$*" | xmllint --format -
